#!/bin/sh
#
# generate a tar.gz archive to distribute
# generate an md5sum and a detached signature of the archive
#
# requires:
# - mercurial (hg)
# - md5sum
# - gnupg

if [ $# -ne 1 -o -e "$1" ] ; then
	echo "usage: gen-dist DEST.tar.gz" 2>&1
	exit 1
fi

dir="${1%/*}"
file="${1##*/}"

hg archive -t tgz "$1"

cd "$dir"
md5sum "$file" >"$file.md5sum"
gpg -ab "$file"
