#!/bin/sh
#
# list the version numbers in several important files
# run this script before generating a release

(
grep '^AC_INIT' /dev/null configure.*
printf "Changelog:"
sed -n '/^[0-9]\.[0-9]\{1,\}\.[0-9]\{1,\}/{p;q}' ChangeLog
printf "NEWS:"
sed -n '/^[0-9]\.[0-9]\{1,\}\.[0-9]\{1,\}/{p;q}' NEWS
grep '^\.TH' /dev/null man/*.[0-9]
) | sed 's~\([^:]*\):.*\([0-9]\.[0-9]\{1,\}\.[0-9]\{1,\}\).*~\2 \1~'
