.TH masqmail.aliases 5 2010-06-21 masqmail-0.2.24 "File Formats"

.SH NAME
masqmail.aliases \- masqmail alias file format


.SH DESCRIPTION

This man page describes the format of the masqmail alias file.
Its usual location is \fI/etc/aliases\fR.


.SH FILE FORMAT

The alias file consists of lines of the form:
local_part: item1, item2, ...
Items can be surrounded by double quotes `"'.
If within the quotes other quotes are needed for an address they can be
escaped with a leading backslash `\\'.

A leading backslash `\\' indicates that this address shall not be further expanded.

A leading pipe symbol `|' indicates that the item shall be treated as a pipe command.
The content of the message will then be sent to the standard input of a command.
The command will run under the user id and group id masqmail is running as.
If quotes are needed, the pipe symbol must appear within the quotes.

Loops will be detected, the offending address will be ignored.

Aliases will be expanded at delivery time.
This means that if there is a message still in the queue and you change
any alias which matches one of the recipient addresses,
the change will have effect next time a delivery is attemped.

There is no need to restart masqmail or run any command when the alias file has been changed.


.SH AUTHOR

Masqmail was written by Oliver Kurth.
It is now maintained by Markus Schnalke <meillo@marmaro.de>.

You will find the newest version of masqmail at \fBhttp://marmaro.de/prog/masqmail/\fR.
There is also a mailing list, you will find information about it at masqmail's main site.


.SH BUGS

Please report bugs to the mailing list.


.SH SEE ALSO

\fBmasqmail.conf(5)\fR, \fBmasqmail(8)\fR, 
