.TH masqmail 8 2010-07-23 masqmail-0.3.0 "Maintenance Commands"

.SH NAME
masqmail \- An offline Mail Transfer Agent

.SH SYNOPSIS
\fB/usr/sbin/masqmail \fR[\fB\-C \fIfile\fR] [\fB\-odq\fR] [\fB\-bd\fR] [\fB\-q\fIinterval\fR]

\fB/usr/sbin/masqmail \fR[\fB\-odq\fR] [\fB\-bs\fR]

\fB/usr/sbin/masqmail \fR[\fB\-bp\fR]

\fB/usr/sbin/masqmail \fR[\fB\-q\fR]

\fB/usr/sbin/masqmail \fR[\fB\-qo \fR[\fIname\fR]]

\fB/usr/sbin/masqmail \fR[\fB\-t\fR] [\fB\-oi\fR] [\fB\-f \fIaddress\fR] [\fB\-\-\fR] \fIaddress...

\fB/usr/sbin/mailq\fR


.SH DESCRIPTION

Masqmail is a mail server designed for hosts that do not have a permanent internet connection
e.g. a home network or a single host at home.
It has special support for connections to different ISPs.
It replaces sendmail or other MTAs such as qmail or exim.


.SH OPTIONS

Since masqmail is intended to replace sendmail, it uses the same command line options,
but not all are implemented.
The \fB\-qo\fP option is additional, and unique to masqmail.

.TP
\fB\-\-\fR

Not a `real' option, it means that all following arguments are to be understood
as arguments and not as options even if they begin with a leading dash `\-'.
Mutt is known to call sendmail with this option.

.TP
\fB\-bd\fR

Run as daemon, accepting connections, usually on port 25 if not configured differently.
This is usually used in the startup script at system boot and together with
the \fB\-q\fR option (see below).

.TP
\fB\-bi\fR

Old sendmail rebuilds its alias database when invoked with this option.
Masqmail ignores it.
Masqmail reads directly from the file given with `alias_file' in the config file.

.TP
\fB\-bp\fR

Show the messages in the queue. Same as calling masqmail as `mailq'.

.TP
\fB\-bs\fR

Accept SMTP commands from stdin.
Some mailers (e.g. pine) use this option as an interface.
It can also be used to call masqmail from inetd.

.TP
\fB\-B \fIarg\fR

\fIarg\fR is usually 8BITMIME.
Some mailers use this to indicate that the message contains characters > 127.
Masqmail is 8-bit clean and ignores this, so you do not have to recompile elm,
which is very painful ;-).
Note though that this violates some conventions:
masqmail does not convert 8 bit messages to any MIME format if it encounters
a mail server which does not advertise its 8BITMIME capability,
masqmail does not advertise this itself.
This is the same practice as that of exim (but different to sendmail).

.TP
\fB\-bV \fR

Show version information.

.TP
\fB\-C \fIfilename\fR

Use another configuration than \fI/etc/masqmail/masqmail.conf\fR.
Useful for debugging purposes.
If not invoked by a privileged user, masqmail will drop all privileges.

.TP
\fB\-d \fInumber\fR

Set the debug level.
This takes precedence before the value of `debug_level' in the configuration file.
Read the warning in the description of the latter.
Only root may set the debug level.

.TP
\fB\-f [\fIaddress\fB]\fR

Set the return path address to \fIaddress\fR.
Only root, the user mail and anyone in group mail is allowed to do that.

.TP
\fB\-F [\fIstring\fB]\fR

Set the full sender name (in the From: header) to \fIstring\fR.

.TP
\fB\-i\fR

Same as \fB\-oi\fR, see below.
Kept for compatibility.

.TP
\fB\-Mrm \fImsgid...\fR

Remove given messages from the queue.
Privileged users may remove any message,
other users only their own.
The message identifiers are listed in the output of
\fImasqmail \-bp\fP (aka. \fImailq\fR).

.TP
\fB\-m\fR

Same as \fB\-om\fR, see below.
Kept for compatibility.

.TP
\fB\-oem\fR

Currently this option makes masqmail behave such:

If the \fB\-oi\fR ist not also given, always return with a non zero return code.

It seems as if this current behavior is not like it should be.

In exim this option makes it behave such:

.in +4
.ll -4
If an error is detected while a non-SMTP message is being received
(for example, a malformed address),
the error is reported to the sender in a mail message.
Exim exits with a non-zero return code then,
no matter if the error message was successful or not.
(In exim, -oee is similar but exim returns successful
if the error message had been sent successful.)
.ll
.in

The mutt wiki writes about ``sendmail -oi -oem'':

.in +4
.ll -4
The mail server (in this case sendmail) will receive the message in input,
and will parse it. In case of a malformed message, it will send an error
message to the user to whom belongs the MUA trasmitting the message
(e.g. user@localhost.localdomain), and it will exit with a non zero exit code:
the -oem flag forces the returning of a non zero exit code even in
the case the error message has been successfully sent to the local server.
.ll
.in

Masqmail's behavior is different in that:
First, it does not send such error messages.
Second, return non-zero whenever -oem is set (but -oi not).
Third, -oi overrules -oem, though as it seems the two options 
should not affect each other.
(Their relationship is just that -oem does only affect non-SMTP
messages on stdin, which is the typical use of -oi.)

.TP
\fB\-odb\fR

``Deliver in Background''
Masqmail always does this.
Hence masqmail ignores this switch.

.TP
\fB\-odq\fR

``Do Queueing''
Do not attempt to deliver immediately.
Any messages will be queued until the next queue running process picks them up and delivers them.
You get the same effect by setting the do_queue option in /etc/masqmail/masqmail.conf.

.TP
\fB\-oi\fR

A dot as a single character in a line does not terminate the message.

.TP
\fB\-om\fR

``Me too''
Masqmail never excludes the sender from any alias expansions,
like if this switch is always set.
Specifying this switch changes nothing.

.TP
\fB\-oXXX\fR

Any other switch starting with `-o' is ignored.

.TP
\fB\-q [\fIinterval\fB]\fR

If not given with an argument, run a queue process, i.e. try to deliver all messages in the queue.
Masqmail sends only to those addresses that are on the local net, not to those that are outside.
Use \fB\-qo\fR for those.

If you have configured inetd to start masqmail,
you can use this option in a cron job which starts in regular time intervals,
to mimic the same effect as starting masqmail with \fB\-bd \-q30m\fR.

An argument may be a time interval i.e. a numerical value followed by one of the letters.
s,m,h,d,w which are interpreted as seconds, minutes, hours, days or weeks respectively.
Example: \fB\-q30m\fR.
Masqmail starts as a daemon and a queue runner process will be started automatically
once in this time interval.
This is usually used together with \fB\-bd\fR (see above).

.TP
\fB\-qo [\fIname\fB]\fR

Can be followed by a connection name.
Use this option in your script which starts as soon as a link to the internet
has been set up (usually ip-up).
When masqmail is called with this option, the specified route configuration
is read and the queued mail with destinations on the internet will be sent.
The \fIname\fR is defined in the configuration (see \fBonline_routes.\fIname\fR).

If called without \fIname\fR the online status is determined with the configured
method (see \fBonline_detect\fR in \fBmasqmail.conf(5)\fR)

.TP
\fB\-t\fR

Read recipients from headers.
If any arguments are given, these are interpreted as recipient addresses
and the message will not be sent to these,
although they might appear in To:, Cc:, or Bcc: headers.
I.e. the set of argument recipients is ``substracted'' from the set of header recipients.

This behavior is similar to exim's and smail's.
Postfix, in contrast, adds the arguments to the set of header recipients.
Sendmail seems to behave differently, depending on the version.
See exim(8) for further information.

.TP
\fB\-v\fR

``Verbose''
Log also to stdout.
Currently, some log messages are marked as `write to stdout' and additionally,
all messages with priority `LOG_ALERT' and `LOG_WARNING' will be written to stdout
if this option is given. It is disabled in daemon mode.


.SH ENVIRONMENT FOR PIPES AND MDAS

For security reasons, before any pipe command from an alias expansion or an mda is called,
the environment variables will be completely discarded and newly set up. These are:

SENDER, RETURN_PATH \(en the return path.

SENDER_DOMAIN \(en the domain part of the return path.

SENDER_LOCAL \(en the local part of the return path.

RECEIVED_HOST \(en the host the message was received from (unless local).

LOCAL_PART, USER, LOGNAME \(en the local part of the (original) recipient.

MESSAGE_ID \(en the unique message id.
This is not necessarily identical with the Message ID as given in the Message ID: header.

QUALIFY_DOMAIN \(en the domain which will be appended to unqualified addresses.


.SH FILES

\fI/etc/masqmail/masqmail.conf\fR is the main configuration for masqmail.
Depending on the settings in this file, you will also have other configuration
files in \fI/etc/masqmail/\fR.

\fI/var/spool/masqmail/\fR is the spool directory where masqmail stores
its spooled messages.

\fI/var/spool/mail/\fR is the directory where locally delivered mail will be put,
if not configured differently in \fImasqmail.conf\fR.

\fI/var/log/masqmail/\fR is the directory where masqmail stores its log mesages.
This can also be somewhere else if configured differently by your sysadmin or the package mantainer.


.SH CONFORMING TO

RFC 821, 822, 1869, 1870, 2197, 2554 (SMTP)

RFC 1321 (MD5)

RFC 2195 (CRAM-MD5)


.SH AUTHOR

Masqmail was written by Oliver Kurth.
It is now maintained by Markus Schnalke <meillo@marmaro.de>.

You will find the newest version of masqmail at \fBhttp://marmaro.de/prog/masqmail/\fR.
There is also a mailing list, you will find information about it at masqmail's main site.


.SH BUGS

Please report them to the mailing list.


.SH SEE ALSO

\fBmasqmail.conf(5)\fR, \fBmasqmail.route(5)\fR, \fBmasqmail.aliases(5)\fR
