.TH mservdetect 1 2011-06-03 masqmail-0.2.29 "User Commands"

.SH NAME
mservdetect \- Helper for masqmail and masqdialer


.SH SYNOPSIS
\fB/usr/bin/mservdetect \fIhost port\fR


.SH DESCRIPTION

Mservdetect is a small helper application for masqmail to detect its online status
if the modem server masqdialer is used.
It connects to the\fIhost\fR at \fIport\fR and prints the connection name to stdout.

If you want to use it, set \fBonline_detect\fR=\fIpipe\fR and
\fBonline_pipe\fR=\fI"/usr/bin/mservdetect host port"\fR in
masqmail.conf.

.SH OPTIONS

.TP
\fBhost\fR

The hostname where the masqdialer server is running.

.TP
\fBport\fR

The port number where the masqdialer server is listening.


.SH AUTHOR

Masqmail was written by Oliver Kurth.
It is now maintained by Markus Schnalke <meillo@marmaro.de>.

You will find the newest version of masqmail at \fBhttp://marmaro.de/prog/masqmail/\fR.
There is also a mailing list, you will find information about it at masqmail's main site.


.SH BUGS

Please report bugs to the mailing list.


.SH SEE ALSO

\fBmasqmail(8)\fR, \fBmasqmail.conf(5)\fR
