#!/bin/sh
#
# try several ways to guess the hostname
# earlier output lines are probably better

(

# this is what Debian uses
cat /etc/mailname

# probably a good value on GNU/Linux
hostname -f

# this is often the short hostname
cat /etc/hostname

# often the short hostname, but widely available
hostname

# this file was mentioned on the Internet
cat /etc/HOSTNAME

) 2>/dev/null | uniq

exit 0
