#!/bin/sh

# path to the masqmail executable
mm_bin=../../src/masqmail

hfrom="\"Fritz Meier\" <$LOGNAME@localhost>"
hto="$hfrom"
to=$LOGNAME@localhost
hsubject="Masqmail test: relay-to-localhost-mta"


# the command to be run:
cmd="$mm_bin -C ./test.conf $to"

$cmd <<EOF
From: $hfrom
To: $hto
Subject: $hsubject

Hallo Fritz!

command was: $cmd

Fritz
.

EOF
