#!/bin/sh
#
# checks if all recognized options are documented
# run from masqmail's repository root dir
#
# Note: this script is far from perfect, but its development time to
#       usage value ratio is quite good :-)

docs="/tmp/masqmail-opts-docs.$$"
code="/tmp/masqmail-opts-code.$$"

cat man/masqmail.*.5.in | sed -n 's,^\.BI "*\([a-z_.]*\).* = ".*,\1,p' |
    sort -u >"$docs"

cat src/conf.c | grep 'lval,.*"' |
    sed 's,[^"]*",,; s,"\, [0-9]*,",; s,".*,,' | sort -u >"$code"

diff -U 0 "$code" "$docs" | grep -v '^@@' |
    sed 's/^---.*/--- code/;s/^+++.*/+++ docs/'

rm -f "$docs" "$code"
